### ISSUE TITLE
Update Chisel to Cricket's version

### ISSUE THREAD

**Issue by Peach774** [Biochao/Automata#3]
As title implies. Personally the version you have in the pack causes issues with optifine but the version you are using is no longer being developed. cricket is actively developing chisel and has added a few new tile sets in the process. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2254671-chisel-2-2-1-0-0

**Comment by Biochao** [comment]
Oh, I see that worlds will transfer now. I was holding off on doing that because the CurseForge page still says blocks will be missing. Should be updated in the next modpack version.

**Comment by Peach774** [comment]
Actually this is only half the problem other half seems to be the forge version. you should change to forge .1232, .1235 is not recommended or done.
