### ISSUE TITLE
Iron tank wall/gauge/valve not recognised in quest

### ISSUE THREAD

**Issue by DavsX** [Biochao/Automata#4]
Hi!
In the Humble beginnings tank quest I need to craft 22 iron tank wall, 3 iron tank gauge and an iron tank valve. I did so, I have 24/8/8 pieces each (more than needed) and I can't progress on that quest; manual detect does not help eighter.

**Comment by Biochao** [comment]
That quest is a Crafting Task so every time you craft a set it counts as one craft. I really should change that to a Detection Task.

**Comment by DavsX** [comment]
So if I understand it correctly: I have to craft iron tank wall 22x times? So that I'd have 22x(number of iron tank walls per craft) of them?

**Comment by Biochao** [comment]
Yep, until the next update.

**Comment by DavsX** [comment]
Thanks  for the update!
